#!/usr/bin/env python3
"""
Translate Phase 1b DSL-constrained hypotheses into our s-expression format.

Phase 1b hypotheses were generated by Gemini Pro in a curried Python-like
DSL format:
    rule = lambda hand: all(lambda card: eq(mod(rank_val(card))(2))(0))(hand)

Our parser expects s-expressions with de Bruijn indices:
    (λ all (λ eq (mod (rank_val $0) 2) 0) $0)

This script:
1. Loads 271 passed Phase 1b DSL-constrained hypotheses
2. Deduplicates against existing 153 injected hypotheses
3. Translates each via Gemini 2.5 Flash with few-shot examples
4. Validates each translation (parse + prior + semantic check)
5. Retries failures with error feedback (max 2 retries)
6. Appends valid translations to injected_hypotheses.json
"""

import json
import glob
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

# Paths relative to this file
_THIS_DIR = Path(__file__).parent
_INJECTED_PATH = _THIS_DIR / "data" / "injected_hypotheses.json"

# Phase 1b results live in the main repo (not this worktree), so we
# resolve the path relative to the git root's sibling main checkout.
# Worktree layout: .worktrees/bayesian-rule-induction/src/gallery_analysis/
# Main repo:       card-games-modelling/llm/results/phase1b/
_MAIN_REPO = _THIS_DIR.parent.parent.parent.parent  # up to card-games-modelling/
_PHASE1B_DIR = _MAIN_REPO / "llm" / "results" / "phase1b"
# Also add the main repo's llm/ to sys.path so we can import translators
_MAIN_LLM_DIR = _MAIN_REPO / "llm"


def load_phase1b_hypotheses() -> List[Dict[str, Any]]:
    """
    Load all passed DSL-constrained hypotheses from Phase 1b results.

    Reads all gemini-pro__dsl-constrained__*.json files from the main repo's
    llm/results/phase1b/ directory, extracts entries where passed=True, and
    structures them with rule_id, NL description, code, confidence, and rank.

    Returns:
        List of dicts with keys: rule_id, nl_description, code, confidence,
        rank, source_model.
    """
    pattern = str(_PHASE1B_DIR / "gemini-pro__dsl-constrained__*.json")
    files = sorted(glob.glob(pattern))
    if not files:
        raise FileNotFoundError(
            f"No Phase 1b files found at {_PHASE1B_DIR}. "
            f"Expected gemini-pro__dsl-constrained__*.json files."
        )

    hypotheses = []
    for fp in files:
        with open(fp) as f:
            data = json.load(f)

        rule_id = data["rule_id"]
        for h in data["hypotheses"]:
            if not h.get("passed"):
                continue
            hypotheses.append({
                "rule_id": rule_id,
                "nl_description": h.get("nl_description", ""),
                "code": h["code"],
                "confidence": h.get("confidence", "UNKNOWN"),
                "rank": h.get("rank", 0),
                "source_model": data.get("source_model", "gemini-pro"),
            })

    return hypotheses


def deduplicate_against_existing(
    hypotheses: List[Dict[str, Any]],
) -> Tuple[List[Dict[str, Any]], int]:
    """
    Remove hypotheses whose NL description already exists in injected_hypotheses.json.

    Comparison is case-insensitive and stripped of whitespace.

    Returns:
        (new_hypotheses, n_duplicates)
    """
    existing_nls = set()
    if _INJECTED_PATH.exists():
        with open(_INJECTED_PATH) as f:
            existing = json.load(f)
        for e in existing:
            origin = e.get("origin", {})
            nl = origin.get("hypothesis_text", "").strip().lower()
            if nl:
                existing_nls.add(nl)

    new = []
    n_dup = 0
    for h in hypotheses:
        nl = h["nl_description"].strip().lower()
        if nl in existing_nls:
            n_dup += 1
        else:
            new.append(h)

    return new, n_dup


if __name__ == "__main__":
    print("Loading Phase 1b DSL-constrained hypotheses...")
    hyps = load_phase1b_hypotheses()
    print(f"  Loaded: {len(hyps)} passed hypotheses")

    new_hyps, n_dup = deduplicate_against_existing(hyps)
    print(f"  Deduplicated: {n_dup} overlaps with existing injected")
    print(f"  New hypotheses to translate: {len(new_hyps)}")

    # Show a few examples
    for h in new_hyps[:3]:
        print(f"\n  [{h['rule_id']}] {h['nl_description']}")
        print(f"    Code: {h['code'][:100]}...")
