#!/usr/bin/env python3
"""
Generate PDF Report of Pre-recorded Tasks
==========================================

Creates a visual PDF report of all pre-recorded tasks for manual inspection.
"""

import json
from pathlib import Path
from datetime import datetime


def create_latex_report():
    """Generate LaTeX source for the PDF report."""

    data_dir = Path(__file__).parent / "data" / "prerecorded_tasks"

    # Load all datasets
    datasets = {}
    for json_file in ['catalogue_tasks.json', 'pretraining_tasks.json']:
        path = data_dir / json_file
        if path.exists():
            with open(path) as f:
                datasets[json_file] = json.load(f)

    # Start LaTeX document
    latex = r"""
\documentclass[10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\usepackage{longtable}
\usepackage{booktabs}
\usepackage{xcolor}
\usepackage{fancyhdr}
\usepackage{hyperref}

\pagestyle{fancy}
\fancyhf{}
\rhead{Pre-recorded Tasks Report}
\lhead{Card Games Modelling}
\rfoot{Page \thepage}

\definecolor{positive}{RGB}{0,128,0}
\definecolor{negative}{RGB}{200,0,0}

\title{Pre-recorded Tasks Visual Inspection Report}
\author{Generated by task\_generation.py}
\date{""" + datetime.now().strftime("%Y-%m-%d %H:%M") + r"""}

\begin{document}
\maketitle

\tableofcontents
\newpage

\section{Overview}

This report shows all pre-recorded tasks generated for reproducible experiments.
Each task has:
\begin{itemize}
    \item \textbf{Training examples}: What the model sees during training (balanced 50\% positive, 50\% negative)
    \item \textbf{Holdout examples}: Used for verification (disjoint from training)
    \item \textbf{Near-miss negatives}: Negatives differ from positives by only ONE card
\end{itemize}

\textbf{Key guarantees:}
\begin{enumerate}
    \item All tasks have equal positives and negatives
    \item Seed positives (used to generate near-miss negatives) are SEPARATE from training positives
    \item Holdout is completely disjoint from training
\end{enumerate}

"""

    # Add each dataset
    for json_file, data in datasets.items():
        dataset_name = json_file.replace('_tasks.json', '').replace('_', ' ').title()

        latex += f"\n\\section{{{dataset_name} Tasks}}\n\n"

        # Summary table
        latex += r"\subsection{Summary}" + "\n\n"
        latex += r"\begin{tabular}{lrrrrr}" + "\n"
        latex += r"\toprule" + "\n"
        latex += r"Task & Train+ & Train- & Hold+ & Hold- & Total \\" + "\n"
        latex += r"\midrule" + "\n"

        for task in data['tasks']:
            name = task['name'].replace('_', r'\_')
            train_pos = task['training_balance']['positives']
            train_neg = task['training_balance']['negatives']
            hold_pos = task['holdout_balance']['positives']
            hold_neg = task['holdout_balance']['negatives']
            total = task['n_training'] + task['n_holdout']

            latex += f"{name} & {train_pos} & {train_neg} & {hold_pos} & {hold_neg} & {total} \\\\\n"

        latex += r"\bottomrule" + "\n"
        latex += r"\end{tabular}" + "\n\n"

        # Detailed view of each task
        latex += r"\subsection{Detailed Task Examples}" + "\n\n"

        for task in data['tasks']:
            task_name = task['name'].replace('_', r'\_')
            latex += f"\\subsubsection{{{task_name}}}\n\n"

            latex += f"\\textbf{{Family}}: {task.get('family', 'N/A')}, "
            latex += f"\\textbf{{Difficulty}}: {task.get('difficulty_level', 0)}\n\n"

            # Show sample training examples
            latex += r"\textbf{Training Examples (first 6):}" + "\n\n"
            latex += r"\begin{small}" + "\n"
            latex += r"\begin{tabular}{p{8cm}l}" + "\n"
            latex += r"\toprule" + "\n"
            latex += r"Hand & Label \\" + "\n"
            latex += r"\midrule" + "\n"

            for ex in task['training_examples'][:6]:
                hand = ex['hand']
                cards_str = ", ".join([f"{c['rank'][:3]}-{c['suit'][0]}" for c in hand])
                label = r"\textcolor{positive}{TRUE}" if ex['label'] else r"\textcolor{negative}{FALSE}"
                # Escape special characters
                cards_str = cards_str.replace('_', r'\_')
                latex += f"{cards_str} & {label} \\\\\n"

            latex += r"\bottomrule" + "\n"
            latex += r"\end{tabular}" + "\n"
            latex += r"\end{small}" + "\n\n"

            # Show sample holdout examples
            latex += r"\textbf{Holdout Examples (first 4):}" + "\n\n"
            latex += r"\begin{small}" + "\n"
            latex += r"\begin{tabular}{p{8cm}l}" + "\n"
            latex += r"\toprule" + "\n"
            latex += r"Hand & Label \\" + "\n"
            latex += r"\midrule" + "\n"

            for ex in task['holdout_examples'][:4]:
                hand = ex['hand']
                cards_str = ", ".join([f"{c['rank'][:3]}-{c['suit'][0]}" for c in hand])
                label = r"\textcolor{positive}{TRUE}" if ex['label'] else r"\textcolor{negative}{FALSE}"
                cards_str = cards_str.replace('_', r'\_')
                latex += f"{cards_str} & {label} \\\\\n"

            latex += r"\bottomrule" + "\n"
            latex += r"\end{tabular}" + "\n"
            latex += r"\end{small}" + "\n\n"

            latex += r"\vspace{0.5cm}" + "\n\n"

    # Add metadata section
    latex += r"\section{Generation Metadata}" + "\n\n"

    for json_file, data in datasets.items():
        dataset_name = json_file.replace('_tasks.json', '').replace('_', ' ').title()
        latex += f"\\subsection{{{dataset_name}}}\n\n"

        metadata = data.get('metadata', {})
        config = data.get('config', {})

        latex += r"\begin{itemize}" + "\n"
        latex += f"\\item Generated: {metadata.get('generated_at', 'N/A')}\n"
        latex += f"\\item Seed: {metadata.get('seed', 'N/A')}\n"
        latex += f"\\item Source: {metadata.get('rule_source', 'N/A').replace('_', ' ')}\n"
        latex += f"\\item Tasks attempted: {metadata.get('n_rules_attempted', 'N/A')}\n"
        latex += f"\\item Tasks generated: {metadata.get('n_tasks_generated', 'N/A')}\n"
        latex += f"\\item Failures: {metadata.get('n_failures', 'N/A')}\n"
        latex += r"\end{itemize}" + "\n\n"

        if metadata.get('failures'):
            latex += r"\textbf{Failed rules:}" + "\n"
            latex += r"\begin{itemize}" + "\n"
            for failure in metadata['failures']:
                rule_id = failure['rule_id'].replace('_', r'\_')
                reason = failure['reason'][:80].replace('_', r'\_') + "..."
                latex += f"\\item {rule_id}: {reason}\n"
            latex += r"\end{itemize}" + "\n\n"

        latex += r"\textbf{Configuration:}" + "\n"
        latex += r"\begin{itemize}" + "\n"
        latex += f"\\item Training positives: {config.get('n_training_positives', 'N/A')}\n"
        latex += f"\\item Training negatives: {config.get('n_training_negatives', 'N/A')}\n"
        latex += f"\\item Seed positives (for near-miss): {config.get('n_seed_positives', 'N/A')}\n"
        latex += f"\\item Holdout positives: {config.get('n_holdout_positives', 'N/A')}\n"
        latex += f"\\item Holdout negatives: {config.get('n_holdout_negatives', 'N/A')}\n"
        latex += f"\\item Near-miss enabled: {config.get('use_near_miss_negatives', 'N/A')}\n"
        latex += f"\\item Max sampling attempts: {config.get('max_sampling_attempts', 'N/A'):,}\n"
        latex += r"\end{itemize}" + "\n\n"

    # End document
    latex += r"\end{document}"

    return latex


def main():
    print("Generating PDF report of pre-recorded tasks...")

    # Generate LaTeX
    latex_content = create_latex_report()

    # Save LaTeX file
    output_dir = Path(__file__).parent / "docs"
    output_dir.mkdir(exist_ok=True)

    tex_path = output_dir / "prerecorded_tasks_report.tex"
    with open(tex_path, 'w') as f:
        f.write(latex_content)
    print(f"LaTeX saved to: {tex_path}")

    # Compile to PDF
    import subprocess
    import os

    os.chdir(output_dir)

    # Run pdflatex twice for TOC
    for i in range(2):
        result = subprocess.run(
            ['/Library/TeX/texbin/pdflatex', '-interaction=nonstopmode', tex_path.name],
            capture_output=True,
            text=True
        )
        if result.returncode != 0 and i == 1:
            print(f"pdflatex warning (may be ok): {result.stderr[:200] if result.stderr else 'none'}")

    pdf_path = output_dir / "prerecorded_tasks_report.pdf"
    if pdf_path.exists():
        print(f"PDF generated: {pdf_path}")
        # Open in Preview/Skim
        subprocess.run(['open', '-a', 'Skim', str(pdf_path)])
        print("Opened in Skim for review")
    else:
        print("PDF generation may have failed, check LaTeX errors")


if __name__ == "__main__":
    main()
